name: Release HelloWorld
on: [pull_request, workflow_dispatch]
 
jobs:
  release-artifact:
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Set variables
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t helloworld:latest .
          docker tag helloworld:latest asia-southeast1-docker.pkg.dev/breu-dev/ctrlplane/helloworld:latest
          docker tag helloworld:latest asia-southeast1-docker.pkg.dev/breu-dev/ctrlplane/helloworld:${{ steps.vars.outputs.short_sha }} 

      - name: docker ls
        run: docker image ls

      - name: Authenticate with GCP
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: "${{ secrets.GCP_WORLDLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SA_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          access_token_lifetime: 300s
          
      - name: Login into Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev/breu-dev/ctrlplane
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            asia-southeast1-docker.pkg.dev/breu-dev/ctrlplane/helloworld:${{ steps.vars.outputs.short_sha }}
          labels: "1.0.0"

      - name: Artifact ready notification
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.breu.ngrok.io/providers/github/artifact-ready'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "X-API-KEY": "${{secrets.QUANTUM_API_KEY}}"}'
          data: '{"image": "asia-southeast1-docker.pkg.dev/breu-dev/ctrlplane/helloworld:${{ steps.vars.outputs.short_sha }}", "repo id": ${{github.repository_id}}, "repo name":${{github.repository}}}'
